/**
 * Material Manifest - Auto-generated
 *
 * This file is automatically generated by scripts/generate-material-manifest.ts
 * DO NOT EDIT MANUALLY
 *
 * Generated: 2025-11-13T00:16:49.020Z
 */

export type MaterialCategory = 'fabric' | 'metal' | 'stone' | 'wood' | 'ceramic' | 'glass' | 'plastic' | 'toon';

export interface MaterialConfig {
  id: string;
  name: string;
  displayName: string;
  category: MaterialCategory;
  thumbnailPath?: string;
  textures?: {
    baseColor?: string;
    normal?: string;
    metallicRoughness?: string;
  };
  properties: {
    roughness: number;
    metallic: number;
    baseColorHex: string;
  };
  tags: string[];
  description: string;
}

export interface CategoryConfig {
  id: MaterialCategory;
  label: string;
  featured: string[];      // Material IDs to show in hover popup (5-8)
  all: string[];            // All material IDs in this category
}

// ─────────────────────────────────────────────────────────────
// Material Definitions
// ─────────────────────────────────────────────────────────────

// FABRIC (8 materials)
const FBR_Canvas_Natural: MaterialConfig = {
  "id": "FBR_Canvas_Natural",
  "name": "Canvas Natural",
  "displayName": "Canvas Natural",
  "category": "fabric",
  "properties": {
    "roughness": 0.8,
    "metallic": 0,
    "baseColorHex": "#e8d7c3"
  },
  "tags": [
    "fabric",
    "canvas",
    "natural"
  ],
  "description": "Natural canvas fabric with matte finish"
};

const FBR_Cotton_White: MaterialConfig = {
  "id": "FBR_Cotton_White",
  "name": "Cotton White",
  "displayName": "Cotton White",
  "category": "fabric",
  "textures": {
    "baseColor": "/assets/materials/fabric/FBR_Cotton_White/BaseColor.png",
    "normal": "/assets/materials/fabric/FBR_Cotton_White/Normal.png",
    "metallicRoughness": "/assets/materials/fabric/FBR_Cotton_White/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.8,
    "metallic": 0,
    "baseColorHex": "#e0e0e0"
  },
  "tags": [
    "fabric",
    "cotton",
    "white"
  ],
  "description": "Cotton White material for 3D scenes with PBR textures"
};

const FBR_Denim_Blue: MaterialConfig = {
  "id": "FBR_Denim_Blue",
  "name": "Denim Blue",
  "displayName": "Denim Blue",
  "category": "fabric",
  "textures": {
    "baseColor": "/assets/materials/fabric/FBR_Denim_Blue/BaseColor.png",
    "normal": "/assets/materials/fabric/FBR_Denim_Blue/Normal.png",
    "metallicRoughness": "/assets/materials/fabric/FBR_Denim_Blue/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.8,
    "metallic": 0,
    "baseColorHex": "#e0e0e0"
  },
  "tags": [
    "fabric",
    "denim",
    "blue"
  ],
  "description": "Denim Blue material for 3D scenes with PBR textures"
};

const FBR_Leather_Brown: MaterialConfig = {
  "id": "FBR_Leather_Brown",
  "name": "Leather Brown",
  "displayName": "Leather Brown",
  "category": "fabric",
  "textures": {
    "baseColor": "/assets/materials/fabric/FBR_Leather_Brown/BaseColor.png",
    "normal": "/assets/materials/fabric/FBR_Leather_Brown/Normal.png",
    "metallicRoughness": "/assets/materials/fabric/FBR_Leather_Brown/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.8,
    "metallic": 0,
    "baseColorHex": "#e0e0e0"
  },
  "tags": [
    "fabric",
    "leather",
    "brown"
  ],
  "description": "Leather Brown material for 3D scenes with PBR textures"
};

const FBR_Linen_Natural: MaterialConfig = {
  "id": "FBR_Linen_Natural",
  "name": "Linen Natural",
  "displayName": "Linen Natural",
  "category": "fabric",
  "textures": {
    "baseColor": "/assets/materials/fabric/FBR_Linen_Natural/BaseColor.png",
    "normal": "/assets/materials/fabric/FBR_Linen_Natural/Normal.png",
    "metallicRoughness": "/assets/materials/fabric/FBR_Linen_Natural/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.8,
    "metallic": 0,
    "baseColorHex": "#e0e0e0"
  },
  "tags": [
    "fabric",
    "linen",
    "natural"
  ],
  "description": "Linen Natural material for 3D scenes with PBR textures"
};

const FBR_Silk_Lustrous: MaterialConfig = {
  "id": "FBR_Silk_Lustrous",
  "name": "Silk Lustrous",
  "displayName": "Silk Lustrous",
  "category": "fabric",
  "textures": {
    "baseColor": "/assets/materials/fabric/FBR_Silk_Lustrous/BaseColor.png",
    "normal": "/assets/materials/fabric/FBR_Silk_Lustrous/Normal.png",
    "metallicRoughness": "/assets/materials/fabric/FBR_Silk_Lustrous/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.8,
    "metallic": 0,
    "baseColorHex": "#e0e0e0"
  },
  "tags": [
    "fabric",
    "silk",
    "lustrous"
  ],
  "description": "Silk Lustrous material for 3D scenes with PBR textures"
};

const FBR_Velvet_Red: MaterialConfig = {
  "id": "FBR_Velvet_Red",
  "name": "Velvet Red",
  "displayName": "Velvet Red",
  "category": "fabric",
  "textures": {
    "baseColor": "/assets/materials/fabric/FBR_Velvet_Red/BaseColor.png",
    "normal": "/assets/materials/fabric/FBR_Velvet_Red/Normal.png",
    "metallicRoughness": "/assets/materials/fabric/FBR_Velvet_Red/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.8,
    "metallic": 0,
    "baseColorHex": "#e0e0e0"
  },
  "tags": [
    "fabric",
    "velvet",
    "red"
  ],
  "description": "Velvet Red material for 3D scenes with PBR textures"
};

const FBR_Wool_Knit: MaterialConfig = {
  "id": "FBR_Wool_Knit",
  "name": "Wool Knit",
  "displayName": "Wool Knit",
  "category": "fabric",
  "textures": {
    "baseColor": "/assets/materials/fabric/FBR_Wool_Knit/BaseColor.png",
    "normal": "/assets/materials/fabric/FBR_Wool_Knit/Normal.png",
    "metallicRoughness": "/assets/materials/fabric/FBR_Wool_Knit/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.8,
    "metallic": 0,
    "baseColorHex": "#e0e0e0"
  },
  "tags": [
    "fabric",
    "wool",
    "knit"
  ],
  "description": "Wool Knit material for 3D scenes with PBR textures"
};

// METAL (8 materials)
const MTL_Aluminum_Brushed: MaterialConfig = {
  "id": "MTL_Aluminum_Brushed",
  "name": "Aluminum Brushed",
  "displayName": "Aluminum Brushed",
  "category": "metal",
  "textures": {
    "baseColor": "/assets/materials/metal/aluminum-brushed.png"
  },
  "properties": {
    "roughness": 0.4,
    "metallic": 1.0,
    "baseColorHex": "#e9ebec"
  },
  "tags": [
    "metal",
    "aluminum",
    "brushed",
    "featured"
  ],
  "description": "Brushed aluminum material with directional finish for 3D scenes"
};

const MTL_Brass_Aged: MaterialConfig = {
  "id": "MTL_Brass_Aged",
  "name": "Brass Aged",
  "displayName": "Brass Aged",
  "category": "metal",
  "textures": {
    "baseColor": "/assets/materials/metal/brass-aged.png"
  },
  "properties": {
    "roughness": 0.35,
    "metallic": 1.0,
    "baseColorHex": "#c7911c"
  },
  "tags": [
    "metal",
    "brass",
    "aged",
    "featured"
  ],
  "description": "Aged brass with patina and warm golden tones"
};

const MTL_Chrome_Mirror: MaterialConfig = {
  "id": "MTL_Chrome_Mirror",
  "name": "Chrome Mirror",
  "displayName": "Chrome Mirror",
  "category": "metal",
  "textures": {
    "baseColor": "/assets/materials/metal/chrome-mirror.png"
  },
  "properties": {
    "roughness": 0.05,
    "metallic": 1.0,
    "baseColorHex": "#e6e6e6"
  },
  "tags": [
    "metal",
    "chrome",
    "mirror",
    "featured"
  ],
  "description": "Highly reflective mirror-finish chrome"
};

const MTL_Copper_Clean: MaterialConfig = {
  "id": "MTL_Copper_Clean",
  "name": "Copper Clean",
  "displayName": "Copper Clean",
  "category": "metal",
  "textures": {
    "baseColor": "/assets/materials/metal/copper-clean.png"
  },
  "properties": {
    "roughness": 0.15,
    "metallic": 1.0,
    "baseColorHex": "#f4a389"
  },
  "tags": [
    "metal",
    "copper",
    "clean",
    "featured"
  ],
  "description": "Clean polished copper with warm reddish-orange tones"
};

const MTL_Gold_Polished: MaterialConfig = {
  "id": "MTL_Gold_Polished",
  "name": "Gold Polished",
  "displayName": "Gold Polished",
  "category": "metal",
  "thumbnailPath": "/assets/materials/metal/gold-polished.png?v=3",
  "textures": {
    "baseColor": "/assets/materials/metal/gold-polished.png"
  },
  "properties": {
    "roughness": 0.1,
    "metallic": 1.0,
    "baseColorHex": "#ffc356"
  },
  "tags": [
    "metal",
    "gold",
    "polished",
    "featured"
  ],
  "description": "Luxurious polished gold with warm reflective finish"
};

const MTL_Iron_Rusty: MaterialConfig = {
  "id": "MTL_Iron_Rusty",
  "name": "Iron Rusty",
  "displayName": "Iron Rusty",
  "category": "metal",
  "textures": {
    "baseColor": "/assets/materials/metal/iron-rusty.png"
  },
  "properties": {
    "roughness": 0.7,
    "metallic": 0.85,
    "baseColorHex": "#734026"
  },
  "tags": [
    "metal",
    "iron",
    "rusty",
    "weathered"
  ],
  "description": "Weathered rusty iron with oxidized patina"
};

const MTL_Steel_Industrial: MaterialConfig = {
  "id": "MTL_Steel_Industrial",
  "name": "Steel Industrial",
  "displayName": "Steel Industrial",
  "category": "metal",
  "textures": {
    "baseColor": "/assets/materials/metal/steel-industrial.png"
  },
  "properties": {
    "roughness": 0.5,
    "metallic": 1.0,
    "baseColorHex": "#8c8c8c"
  },
  "tags": [
    "metal",
    "steel",
    "industrial",
    "featured"
  ],
  "description": "Industrial steel with semi-rough matte finish"
};

const MTL_Titanium_Anodized: MaterialConfig = {
  "id": "MTL_Titanium_Anodized",
  "name": "Titanium Anodized",
  "displayName": "Titanium Anodized",
  "category": "metal",
  "textures": {
    "baseColor": "/assets/materials/metal/titanium-anodized.png"
  },
  "properties": {
    "roughness": 0.25,
    "metallic": 1.0,
    "baseColorHex": "#6673a6"
  },
  "tags": [
    "metal",
    "titanium",
    "anodized",
    "featured"
  ],
  "description": "Anodized titanium with blue-purple iridescent tones"
};

// STONE (8 materials)
const STN_Cobblestone_Street: MaterialConfig = {
  "id": "STN_Cobblestone_Street",
  "name": "Cobblestone Street",
  "displayName": "Cobblestone Street",
  "category": "stone",
  "textures": {
    "baseColor": "/assets/materials/stone/STN_Cobblestone_Street/BaseColor.png",
    "normal": "/assets/materials/stone/STN_Cobblestone_Street/Normal.png",
    "metallicRoughness": "/assets/materials/stone/STN_Cobblestone_Street/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.6,
    "metallic": 0,
    "baseColorHex": "#a0a0a0"
  },
  "tags": [
    "stone",
    "cobblestone",
    "street"
  ],
  "description": "Cobblestone Street material for 3D scenes with PBR textures"
};

const STN_Concrete_Industrial: MaterialConfig = {
  "id": "STN_Concrete_Industrial",
  "name": "Concrete Industrial",
  "displayName": "Concrete Industrial",
  "category": "stone",
  "textures": {
    "baseColor": "/assets/materials/stone/STN_Concrete_Industrial/BaseColor.png",
    "normal": "/assets/materials/stone/STN_Concrete_Industrial/Normal.png",
    "metallicRoughness": "/assets/materials/stone/STN_Concrete_Industrial/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.6,
    "metallic": 0,
    "baseColorHex": "#a0a0a0"
  },
  "tags": [
    "stone",
    "concrete",
    "industrial"
  ],
  "description": "Concrete Industrial material for 3D scenes with PBR textures"
};

const STN_Granite_Polished: MaterialConfig = {
  "id": "STN_Granite_Polished",
  "name": "Granite Polished",
  "displayName": "Granite Polished",
  "category": "stone",
  "textures": {
    "baseColor": "/assets/materials/stone/STN_Granite_Polished/BaseColor.png",
    "normal": "/assets/materials/stone/STN_Granite_Polished/Normal.png",
    "metallicRoughness": "/assets/materials/stone/STN_Granite_Polished/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.6,
    "metallic": 0,
    "baseColorHex": "#a0a0a0"
  },
  "tags": [
    "stone",
    "granite",
    "polished"
  ],
  "description": "Granite Polished material for 3D scenes with PBR textures"
};

const STN_Lava_Volcanic: MaterialConfig = {
  "id": "STN_Lava_Volcanic",
  "name": "Lava Volcanic",
  "displayName": "Lava Volcanic",
  "category": "stone",
  "textures": {
    "baseColor": "/assets/materials/stone/STN_Lava_Volcanic/BaseColor.png",
    "normal": "/assets/materials/stone/STN_Lava_Volcanic/Normal.png",
    "metallicRoughness": "/assets/materials/stone/STN_Lava_Volcanic/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.6,
    "metallic": 0,
    "baseColorHex": "#a0a0a0"
  },
  "tags": [
    "stone",
    "lava",
    "volcanic"
  ],
  "description": "Lava Volcanic material for 3D scenes with PBR textures"
};

const STN_Limestone_Natural: MaterialConfig = {
  "id": "STN_Limestone_Natural",
  "name": "Limestone Natural",
  "displayName": "Limestone Natural",
  "category": "stone",
  "textures": {
    "baseColor": "/assets/materials/stone/STN_Limestone_Natural/BaseColor.png",
    "normal": "/assets/materials/stone/STN_Limestone_Natural/Normal.png",
    "metallicRoughness": "/assets/materials/stone/STN_Limestone_Natural/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.6,
    "metallic": 0,
    "baseColorHex": "#a0a0a0"
  },
  "tags": [
    "stone",
    "limestone",
    "natural"
  ],
  "description": "Limestone Natural material for 3D scenes with PBR textures"
};

const STN_Marble_Carrara: MaterialConfig = {
  "id": "STN_Marble_Carrara",
  "name": "Marble Carrara",
  "displayName": "Marble Carrara",
  "category": "stone",
  "textures": {
    "baseColor": "/assets/materials/stone/STN_Marble_Carrara/BaseColor.png",
    "normal": "/assets/materials/stone/STN_Marble_Carrara/Normal.png",
    "metallicRoughness": "/assets/materials/stone/STN_Marble_Carrara/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.6,
    "metallic": 0,
    "baseColorHex": "#a0a0a0"
  },
  "tags": [
    "stone",
    "marble",
    "carrara"
  ],
  "description": "Marble Carrara material for 3D scenes with PBR textures"
};

const STN_Sandstone_Desert: MaterialConfig = {
  "id": "STN_Sandstone_Desert",
  "name": "Sandstone Desert",
  "displayName": "Sandstone Desert",
  "category": "stone",
  "textures": {
    "baseColor": "/assets/materials/stone/STN_Sandstone_Desert/BaseColor.png",
    "normal": "/assets/materials/stone/STN_Sandstone_Desert/Normal.png",
    "metallicRoughness": "/assets/materials/stone/STN_Sandstone_Desert/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.6,
    "metallic": 0,
    "baseColorHex": "#a0a0a0"
  },
  "tags": [
    "stone",
    "sandstone",
    "desert"
  ],
  "description": "Sandstone Desert material for 3D scenes with PBR textures"
};

const STN_Slate_Dark: MaterialConfig = {
  "id": "STN_Slate_Dark",
  "name": "Slate Dark",
  "displayName": "Slate Dark",
  "category": "stone",
  "textures": {
    "baseColor": "/assets/materials/stone/STN_Slate_Dark/BaseColor.png",
    "normal": "/assets/materials/stone/STN_Slate_Dark/Normal.png",
    "metallicRoughness": "/assets/materials/stone/STN_Slate_Dark/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.6,
    "metallic": 0,
    "baseColorHex": "#a0a0a0"
  },
  "tags": [
    "stone",
    "slate",
    "dark"
  ],
  "description": "Slate Dark material for 3D scenes with PBR textures"
};

// WOOD (8 materials)
const WOD_Bamboo_Natural: MaterialConfig = {
  "id": "WOD_Bamboo_Natural",
  "name": "Bamboo Natural",
  "displayName": "Bamboo Natural",
  "category": "wood",
  "textures": {
    "baseColor": "/assets/materials/wood/WOD_Bamboo_Natural/BaseColor.png",
    "normal": "/assets/materials/wood/WOD_Bamboo_Natural/Normal.png",
    "metallicRoughness": "/assets/materials/wood/WOD_Bamboo_Natural/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.4000000059604645,
    "metallic": 0,
    "baseColorHex": "#d8bf8c"
  },
  "tags": [
    "wood",
    "bamboo",
    "natural"
  ],
  "description": "Bamboo Natural material exported from Blender at 4096x4096 resolution"
};

const WOD_Mahogany_Rich: MaterialConfig = {
  "id": "WOD_Mahogany_Rich",
  "name": "Mahogany Rich",
  "displayName": "Mahogany Rich",
  "category": "wood",
  "textures": {
    "baseColor": "/assets/materials/wood/WOD_Mahogany_Rich/BaseColor.png",
    "normal": "/assets/materials/wood/WOD_Mahogany_Rich/Normal.png",
    "metallicRoughness": "/assets/materials/wood/WOD_Mahogany_Rich/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.5,
    "metallic": 0,
    "baseColorHex": "#cccccc"
  },
  "tags": [
    "wood",
    "mahogany",
    "rich"
  ],
  "description": "Mahogany Rich material exported from Blender at 4096x4096 resolution"
};

const WOD_Oak_Natural: MaterialConfig = {
  "id": "WOD_Oak_Natural",
  "name": "Oak Natural",
  "displayName": "Oak Natural",
  "category": "wood",
  "textures": {
    "baseColor": "/assets/materials/wood/WOD_Oak_Natural/BaseColor.png",
    "normal": "/assets/materials/wood/WOD_Oak_Natural/Normal.png",
    "metallicRoughness": "/assets/materials/wood/WOD_Oak_Natural/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.5,
    "metallic": 0,
    "baseColorHex": "#cccccc"
  },
  "tags": [
    "wood",
    "oak",
    "natural"
  ],
  "description": "Oak Natural material exported from Blender at 4096x4096 resolution"
};

const WOD_Pine_Knotty: MaterialConfig = {
  "id": "WOD_Pine_Knotty",
  "name": "Pine Knotty",
  "displayName": "Pine Knotty",
  "category": "wood",
  "textures": {
    "baseColor": "/assets/materials/wood/WOD_Pine_Knotty/BaseColor.png",
    "normal": "/assets/materials/wood/WOD_Pine_Knotty/Normal.png",
    "metallicRoughness": "/assets/materials/wood/WOD_Pine_Knotty/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.5,
    "metallic": 0,
    "baseColorHex": "#cccccc"
  },
  "tags": [
    "wood",
    "pine",
    "knotty"
  ],
  "description": "Pine Knotty material exported from Blender at 4096x4096 resolution"
};

const WOD_Polished_Lacquered: MaterialConfig = {
  "id": "WOD_Polished_Lacquered",
  "name": "Polished Lacquered",
  "displayName": "Polished Lacquered",
  "category": "wood",
  "textures": {
    "baseColor": "/assets/materials/wood/WOD_Polished_Lacquered/BaseColor.png",
    "normal": "/assets/materials/wood/WOD_Polished_Lacquered/Normal.png",
    "metallicRoughness": "/assets/materials/wood/WOD_Polished_Lacquered/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.15000000596046448,
    "metallic": 0,
    "baseColorHex": "#cccccc"
  },
  "tags": [
    "wood",
    "polished",
    "lacquered"
  ],
  "description": "Polished Lacquered material exported from Blender at 4096x4096 resolution"
};

const WOD_Reclaimed_Industrial: MaterialConfig = {
  "id": "WOD_Reclaimed_Industrial",
  "name": "Reclaimed Industrial",
  "displayName": "Reclaimed Industrial",
  "category": "wood",
  "textures": {
    "baseColor": "/assets/materials/wood/WOD_Reclaimed_Industrial/BaseColor.png",
    "normal": "/assets/materials/wood/WOD_Reclaimed_Industrial/Normal.png",
    "metallicRoughness": "/assets/materials/wood/WOD_Reclaimed_Industrial/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.5,
    "metallic": 0,
    "baseColorHex": "#cccccc"
  },
  "tags": [
    "wood",
    "reclaimed",
    "industrial"
  ],
  "description": "Reclaimed Industrial material exported from Blender at 4096x4096 resolution"
};

const WOD_Walnut_Dark: MaterialConfig = {
  "id": "WOD_Walnut_Dark",
  "name": "Walnut Dark",
  "displayName": "Walnut Dark",
  "category": "wood",
  "textures": {
    "baseColor": "/assets/materials/wood/WOD_Walnut_Dark/BaseColor.png",
    "normal": "/assets/materials/wood/WOD_Walnut_Dark/Normal.png",
    "metallicRoughness": "/assets/materials/wood/WOD_Walnut_Dark/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.5,
    "metallic": 0,
    "baseColorHex": "#cccccc"
  },
  "tags": [
    "wood",
    "walnut",
    "dark"
  ],
  "description": "Walnut Dark material exported from Blender at 4096x4096 resolution"
};

const WOD_Weathered_Barn: MaterialConfig = {
  "id": "WOD_Weathered_Barn",
  "name": "Weathered Barn",
  "displayName": "Weathered Barn",
  "category": "wood",
  "textures": {
    "baseColor": "/assets/materials/wood/WOD_Weathered_Barn/BaseColor.png",
    "normal": "/assets/materials/wood/WOD_Weathered_Barn/Normal.png",
    "metallicRoughness": "/assets/materials/wood/WOD_Weathered_Barn/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.5,
    "metallic": 0,
    "baseColorHex": "#cccccc"
  },
  "tags": [
    "wood",
    "weathered",
    "barn"
  ],
  "description": "Weathered Barn material exported from Blender at 4096x4096 resolution"
};

// GLASS (8 materials)
const GLS_Clear_Standard: MaterialConfig = {
  "id": "GLS_Clear_Standard",
  "name": "Clear Standard",
  "displayName": "Clear Glass",
  "category": "glass",
  "textures": {
    "baseColor": "/assets/materials/glass/GLS_Clear_Standard/BaseColor.png",
    "normal": "/assets/materials/glass/GLS_Clear_Standard/Normal.png",
    "metallicRoughness": "/assets/materials/glass/GLS_Clear_Standard/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.05,
    "metallic": 0,
    "baseColorHex": "#f4fbff"
  },
  "tags": [
    "glass",
    "clear",
    "transparent",
    "polished"
  ],
  "description": "Clear architectural glass with subtle reflections."
};

const GLS_Colored_Amber: MaterialConfig = {
  "id": "GLS_Colored_Amber",
  "name": "Colored Amber",
  "displayName": "Amber Glass",
  "category": "glass",
  "textures": {
    "baseColor": "/assets/materials/glass/GLS_Colored_Amber/BaseColor.png",
    "normal": "/assets/materials/glass/GLS_Colored_Amber/Normal.png",
    "metallicRoughness": "/assets/materials/glass/GLS_Colored_Amber/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.12,
    "metallic": 0,
    "baseColorHex": "#f8d4a5"
  },
  "tags": [
    "glass",
    "amber",
    "warm",
    "decorative"
  ],
  "description": "Warm amber decorative glass with subtle glow."
};

const GLS_Colored_Blue: MaterialConfig = {
  "id": "GLS_Colored_Blue",
  "name": "Colored Blue",
  "displayName": "Blue Glass",
  "category": "glass",
  "textures": {
    "baseColor": "/assets/materials/glass/GLS_Colored_Blue/BaseColor.png",
    "normal": "/assets/materials/glass/GLS_Colored_Blue/Normal.png",
    "metallicRoughness": "/assets/materials/glass/GLS_Colored_Blue/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.08,
    "metallic": 0,
    "baseColorHex": "#c3e4ff"
  },
  "tags": [
    "glass",
    "blue",
    "accent",
    "architectural"
  ],
  "description": "Cool blue accent glass for lighting and architectural details."
};

const GLS_Colored_Green: MaterialConfig = {
  "id": "GLS_Colored_Green",
  "name": "Colored Green",
  "displayName": "Green Glass",
  "category": "glass",
  "textures": {
    "baseColor": "/assets/materials/glass/GLS_Colored_Green/BaseColor.png",
    "normal": "/assets/materials/glass/GLS_Colored_Green/Normal.png",
    "metallicRoughness": "/assets/materials/glass/GLS_Colored_Green/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.08,
    "metallic": 0,
    "baseColorHex": "#a8e6a1"
  },
  "tags": [
    "glass",
    "green",
    "accent",
    "decorative"
  ],
  "description": "Vibrant green glass for decorative and accent pieces."
};

const GLS_Frosted_Satin: MaterialConfig = {
  "id": "GLS_Frosted_Satin",
  "name": "Frosted Satin",
  "displayName": "Frosted Satin",
  "category": "glass",
  "textures": {
    "baseColor": "/assets/materials/glass/GLS_Frosted_Satin/BaseColor.png",
    "normal": "/assets/materials/glass/GLS_Frosted_Satin/Normal.png",
    "metallicRoughness": "/assets/materials/glass/GLS_Frosted_Satin/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.35,
    "metallic": 0,
    "baseColorHex": "#dfe7ee"
  },
  "tags": [
    "glass",
    "frosted",
    "diffuse",
    "privacy"
  ],
  "description": "Frosted satin glass with soft diffusion for privacy panels."
};

const GLS_Stained_Red: MaterialConfig = {
  "id": "GLS_Stained_Red",
  "name": "Stained Red",
  "displayName": "Red Stained Glass",
  "category": "glass",
  "textures": {
    "baseColor": "/assets/materials/glass/GLS_Stained_Red/BaseColor.png",
    "normal": "/assets/materials/glass/GLS_Stained_Red/Normal.png",
    "metallicRoughness": "/assets/materials/glass/GLS_Stained_Red/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.12,
    "metallic": 0,
    "baseColorHex": "#d94848"
  },
  "tags": [
    "glass",
    "red",
    "stained",
    "artistic"
  ],
  "description": "Rich red stained glass for traditional and artistic applications."
};

const GLS_Textured_Ripple: MaterialConfig = {
  "id": "GLS_Textured_Ripple",
  "name": "Textured Ripple",
  "displayName": "Ripple Glass",
  "category": "glass",
  "textures": {
    "baseColor": "/assets/materials/glass/GLS_Textured_Ripple/BaseColor.png",
    "normal": "/assets/materials/glass/GLS_Textured_Ripple/Normal.png",
    "metallicRoughness": "/assets/materials/glass/GLS_Textured_Ripple/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.25,
    "metallic": 0,
    "baseColorHex": "#e8f4f8"
  },
  "tags": [
    "glass",
    "textured",
    "ripple",
    "privacy"
  ],
  "description": "Textured glass with ripple pattern for privacy and decorative uses."
};

const GLS_Tinted_Smoke: MaterialConfig = {
  "id": "GLS_Tinted_Smoke",
  "name": "Tinted Smoke",
  "displayName": "Tinted Smoke",
  "category": "glass",
  "textures": {
    "baseColor": "/assets/materials/glass/GLS_Tinted_Smoke/BaseColor.png",
    "normal": "/assets/materials/glass/GLS_Tinted_Smoke/Normal.png",
    "metallicRoughness": "/assets/materials/glass/GLS_Tinted_Smoke/MetallicRoughness.png"
  },
  "properties": {
    "roughness": 0.15,
    "metallic": 0,
    "baseColorHex": "#b0c4cc"
  },
  "tags": [
    "glass",
    "tinted",
    "smoke",
    "modern"
  ],
  "description": "Smoked gray glass great for modern interiors."
};

// NEW PRESETS (Added manually)
const MTL_Silver_Polished: MaterialConfig = {
  "id": "MTL_Silver_Polished",
  "name": "Silver Polished",
  "displayName": "Silver Polished",
  "category": "metal",
  "properties": {
    "roughness": 0.1,
    "metallic": 1.0,
    "baseColorHex": "#c0c0c0"
  },
  "tags": ["metal", "silver", "polished", "featured"],
  "thumbnailPath": "/assets/materials/metal/silver-polished.png?v=3",
  "description": "Polished silver with high reflectivity"
};

const MTL_Copper_Polished: MaterialConfig = {
  "id": "MTL_Copper_Polished",
  "name": "Copper Polished",
  "displayName": "Copper Polished",
  "category": "metal",
  "properties": {
    "roughness": 0.2,
    "metallic": 1.0,
    "baseColorHex": "#b87333"
  },
  "tags": ["metal", "copper", "polished", "featured"],
  "thumbnailPath": "/assets/materials/metal/copper-polished.png?v=3",
  "description": "Polished copper with warm tones"
};

const MTL_Iron_Rough: MaterialConfig = {
  "id": "MTL_Iron_Rough",
  "name": "Iron Rough",
  "displayName": "Iron Rough",
  "category": "metal",
  "properties": {
    "roughness": 0.7,
    "metallic": 1.0,
    "baseColorHex": "#4d4d4d"
  },
  "tags": ["metal", "iron", "rough", "featured"],
  "thumbnailPath": "/assets/materials/metal/iron-rough.png?v=3",
  "description": "Rough iron with matte finish"
};

// ─────────────────────────────────────────────────────────────
// Materials Map
// ─────────────────────────────────────────────────────────────

export const MATERIALS: Record<string, MaterialConfig> = {
  'FBR_Canvas_Natural': FBR_Canvas_Natural,
  'FBR_Cotton_White': FBR_Cotton_White,
  'FBR_Denim_Blue': FBR_Denim_Blue,
  'FBR_Leather_Brown': FBR_Leather_Brown,
  'FBR_Linen_Natural': FBR_Linen_Natural,
  'FBR_Silk_Lustrous': FBR_Silk_Lustrous,
  'FBR_Velvet_Red': FBR_Velvet_Red,
  'FBR_Wool_Knit': FBR_Wool_Knit,
  'MTL_Aluminum_Brushed': MTL_Aluminum_Brushed,
  'MTL_Brass_Aged': MTL_Brass_Aged,
  'MTL_Chrome_Mirror': MTL_Chrome_Mirror,
  'MTL_Copper_Clean': MTL_Copper_Clean,
  'MTL_Gold_Polished': MTL_Gold_Polished,
  'MTL_Iron_Rusty': MTL_Iron_Rusty,
  'MTL_Steel_Industrial': MTL_Steel_Industrial,
  'MTL_Titanium_Anodized': MTL_Titanium_Anodized,
  'STN_Cobblestone_Street': STN_Cobblestone_Street,
  'STN_Concrete_Industrial': STN_Concrete_Industrial,
  'STN_Granite_Polished': STN_Granite_Polished,
  'STN_Lava_Volcanic': STN_Lava_Volcanic,
  'STN_Limestone_Natural': STN_Limestone_Natural,
  'STN_Marble_Carrara': STN_Marble_Carrara,
  'STN_Sandstone_Desert': STN_Sandstone_Desert,
  'STN_Slate_Dark': STN_Slate_Dark,
  'WOD_Bamboo_Natural': WOD_Bamboo_Natural,
  'WOD_Mahogany_Rich': WOD_Mahogany_Rich,
  'WOD_Oak_Natural': WOD_Oak_Natural,
  'WOD_Pine_Knotty': WOD_Pine_Knotty,
  'WOD_Polished_Lacquered': WOD_Polished_Lacquered,
  'WOD_Reclaimed_Industrial': WOD_Reclaimed_Industrial,
  'WOD_Walnut_Dark': WOD_Walnut_Dark,
  'WOD_Weathered_Barn': WOD_Weathered_Barn,
  'GLS_Clear_Standard': GLS_Clear_Standard,
  'GLS_Colored_Amber': GLS_Colored_Amber,
  'GLS_Colored_Blue': GLS_Colored_Blue,
  'GLS_Colored_Green': GLS_Colored_Green,
  'GLS_Frosted_Satin': GLS_Frosted_Satin,
  'GLS_Stained_Red': GLS_Stained_Red,
  'GLS_Textured_Ripple': GLS_Textured_Ripple,
  'GLS_Tinted_Smoke': GLS_Tinted_Smoke,
  'MTL_Silver_Polished': MTL_Silver_Polished,
  'MTL_Copper_Polished': MTL_Copper_Polished,
  'MTL_Iron_Rough': MTL_Iron_Rough,
};

// ─────────────────────────────────────────────────────────────
// Category Configurations
// ─────────────────────────────────────────────────────────────

export const CATEGORIES: Record<MaterialCategory, CategoryConfig> = {
  fabric: {
    id: 'fabric',
    label: 'Fabric',
    featured: ["FBR_Canvas_Natural", "FBR_Cotton_White", "FBR_Denim_Blue", "FBR_Leather_Brown", "FBR_Linen_Natural"],
    all: ["FBR_Canvas_Natural", "FBR_Cotton_White", "FBR_Denim_Blue", "FBR_Leather_Brown", "FBR_Linen_Natural", "FBR_Silk_Lustrous", "FBR_Velvet_Red", "FBR_Wool_Knit"]
  },
  metal: {
    id: 'metal',
    label: 'Metal',
    featured: ["MTL_Aluminum_Brushed", "MTL_Gold_Polished", "MTL_Silver_Polished", "MTL_Copper_Polished", "MTL_Iron_Rough"],
    all: ["MTL_Aluminum_Brushed", "MTL_Brass_Aged", "MTL_Chrome_Mirror", "MTL_Copper_Clean", "MTL_Gold_Polished", "MTL_Iron_Rusty", "MTL_Steel_Industrial", "MTL_Titanium_Anodized", "MTL_Silver_Polished", "MTL_Copper_Polished", "MTL_Iron_Rough"]
  },
  stone: {
    id: 'stone',
    label: 'Stone',
    featured: ["STN_Cobblestone_Street", "STN_Concrete_Industrial", "STN_Granite_Polished", "STN_Lava_Volcanic", "STN_Limestone_Natural"],
    all: ["STN_Cobblestone_Street", "STN_Concrete_Industrial", "STN_Granite_Polished", "STN_Lava_Volcanic", "STN_Limestone_Natural", "STN_Marble_Carrara", "STN_Sandstone_Desert", "STN_Slate_Dark"]
  },
  wood: {
    id: 'wood',
    label: 'Wood',
    featured: ["WOD_Bamboo_Natural", "WOD_Mahogany_Rich", "WOD_Oak_Natural", "WOD_Pine_Knotty", "WOD_Polished_Lacquered"],
    all: ["WOD_Bamboo_Natural", "WOD_Mahogany_Rich", "WOD_Oak_Natural", "WOD_Pine_Knotty", "WOD_Polished_Lacquered", "WOD_Reclaimed_Industrial", "WOD_Walnut_Dark", "WOD_Weathered_Barn"]
  },
  ceramic: {
    id: 'ceramic',
    label: 'Ceramic',
    featured: [],
    all: []
  },
  glass: {
    id: 'glass',
    label: 'Glass',
    featured: ["GLS_Clear_Standard", "GLS_Colored_Amber", "GLS_Colored_Blue", "GLS_Colored_Green", "GLS_Frosted_Satin"],
    all: ["GLS_Clear_Standard", "GLS_Colored_Amber", "GLS_Colored_Blue", "GLS_Colored_Green", "GLS_Frosted_Satin", "GLS_Stained_Red", "GLS_Textured_Ripple", "GLS_Tinted_Smoke"]
  },
  plastic: {
    id: 'plastic',
    label: 'Plastic',
    featured: [],
    all: []
  },
  toon: {
    id: 'toon',
    label: 'Toon',
    featured: [],
    all: []
  },
};

// ─────────────────────────────────────────────────────────────
// Helper Functions
// ─────────────────────────────────────────────────────────────

/**
 * Get material by ID
 */
export function getMaterial(id: string): MaterialConfig | undefined {
  return MATERIALS[id];
}

/**
 * Get all materials in a category
 */
export function getCategoryMaterials(category: MaterialCategory): MaterialConfig[] {
  const categoryConfig = CATEGORIES[category];
  return categoryConfig.all.map(id => MATERIALS[id]).filter(Boolean);
}

/**
 * Get featured materials for a category (shown in hover popup)
 */
export function getFeaturedMaterials(category: MaterialCategory): MaterialConfig[] {
  const categoryConfig = CATEGORIES[category];
  return categoryConfig.featured.map(id => MATERIALS[id]).filter(Boolean);
}

/**
 * Search materials by name or tags
 */
export function searchMaterials(query: string): MaterialConfig[] {
  const lowerQuery = query.toLowerCase();
  return Object.values(MATERIALS).filter(material => {
    return (
      material.name.toLowerCase().includes(lowerQuery) ||
      material.displayName.toLowerCase().includes(lowerQuery) ||
      material.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
    );
  });
}

/**
 * Get active categories (categories with at least one material)
 */
export function getActiveCategories(): MaterialCategory[] {
  return Object.keys(CATEGORIES).filter(
    category => CATEGORIES[category as MaterialCategory].all.length > 0
  ) as MaterialCategory[];
}
